name: Android CI

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use a Linux environment for the job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Recommended distribution
          java-version: '11' # Use Java 11 as specified in your build.gradle files
          cache: 'gradle' # Cache Gradle dependencies for faster builds

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # Ensure the Gradle wrapper is executable

      - name: Run Unit Tests for all modules
        run: ./gradlew test # Command to run all unit tests in your project
        # This will run tests for both payrails-lib and payrailssample
        # You can specify individual modules like: ./gradlew :payrails-lib:test :payrailssample:test

      # Optional: If want to run Android Lint checks
#      - name: Run Lint checks
#        run: ./gradlew lint

      # Optional: If want to build the debug APK
#      - name: Build Debug APK
#        run: ./gradlew assembleDebug

      # Optional: To upload test reports as artifacts
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            **/build/reports/tests/testDebugUnitTest/
            **/build/reports/lint-results.html
